### ISSUE TITLE
Getting this error and it is running again and again in a loop

### ISSUE THREAD

**Issue by WingCode** [kimfalk/live-project#4]
python3 populate_moviegeek.py
```
Starting MovieGeeks Population script...
truncate db
finished truncate db
movie data downloaded
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 36101/36384 [05:45<00:02, 121.26it/s]Traceback (most recent call last):
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(128)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "populate_moviegeek.py", line 69, in <module>
    populate()
  File "populate_moviegeek.py", line 63, in populate
    create_movie(m[0], m[1], m[2])
  File "populate_moviegeek.py", line 28, in create_movie
    movie.save()
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(128)

Exception ignored in: <bound method tqdm.__del__ of  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 36101/36384 [05:45<00:02, 121.26it/s]>
Traceback (most recent call last):
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/Users/wing/miniconda3/envs/prs/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

**Comment by yibum** [comment]
I have the same issue when firing up with the docker. And this process and the next populate (rating) would take a lot of time.

What I was doing is that commented  both commands in the docker file, and firing them by getting in the docker container `docker exec -it dockerid bash`.

**Comment by WingCode** [comment]
@yibum I have found the fix for it and have raised a pull request.
